CONNECTION_STATUS = {
    "STARTING": "STARTING",
    "LOADING": "LOADING",
    "DISCONNECTED": "DISCONNECTED",
    "GETTING_JWT": "GETTING_JWT",
    "CONNECTING_SOCKET": "CONNECTING_SOCKET",
    "CONNECTED": "CONNECTED",
    "TIMEOUT": "TIMEOUT",
    "SOCKET_ERROR": "SOCKET_ERROR",
    "ERROR": "ERROR",
}
